accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts.views import signup
# from .views import create_user


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("accounts/", include("accounts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home")), name="home_page"),

]

receipts/urls.py
from django.urls import path
from receipts.views import (
    ReceiptListView, ReceiptRedirectView,
    ReceiptCreateView,
    ExpenseCategoryListView,
    ExpenseCategoryCreateView,
    AccountCreateView,
    AccountListView,



)

urlpatterns = [
    path('', ReceiptListView.as_view(), name="home"),
    path('', ReceiptRedirectView.as_view()),
    path('create/', ReceiptCreateView.as_view(), name="create_receipt"),
    path('categories/', ExpenseCategoryListView.as_view(),
         name="list_categories"),
    path("accounts/", AccountListView.as_view(), name="list_accounts"),
    path("accounts/create/", AccountCreateView.as_view(),
         name="create_account"),
    path("categories/create/", ExpenseCategoryCreateView.as_view(),
         name="create_category")
]

accounts/models.py
# from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

# USER_MODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              related_name='categories',
                              on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              related_name="accounts",
                              on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(settings.AUTH_USER_MODEL,
                                  related_name="receipts",
                                  on_delete=models.CASCADE)
    category = models.ForeignKey(ExpenseCategory, related_name="receipts",
                                 on_delete=models.CASCADE)
    account = models.ForeignKey(Account, related_name="receipts",
                                on_delete=models.CASCADE, null=True)

accounts/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150,
                               widget=forms.PasswordInput)


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150,
                               widget=forms.PasswordInput)
    password_confirmation = forms.CharField(max_length=150,
                                            widget=forms.PasswordInput)

accounts/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm, SignUpForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home")
    else:
        form = LoginForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def user_logout(request):
    logout(request)
    return redirect("home")


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]

            if password == password_confirmation:
                user = User.objects.create_user(
                    username,
                    password=password,
                )

                login(request, user)
                return redirect("home")
            else:
                form.add_error("password", "Passwords do not match")
    else:
        form = SignUpForm()
    context = {
        "form": form,
    }

    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.base import RedirectView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Account, ExpenseCategory, Receipt


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptRedirectView(RedirectView):
    url = "/receipts/"
    pattern_name = "home"


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create_receipt.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "categories/list_categories.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    fields = ["name"]
    template_name = "receipts/create_category.html"

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_categories")


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list_accounts.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/create_account.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_accounts")

    # def receipt_list_view(request):
#     receipts = Receipt.objects.all()
#     context = {"receipts": receipts}
#     return render(request, "receipts/list.html", context

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <nav>
            <ul>
              {% if user.is_authenticated %}
              <li><a href="{% url 'logout' %}">Logout</a></li>
              {% endif %} {% if user.is_anonymous %}
              <li><a href="{% url 'signup' %}">Signup</a></li>
              {% endif %} {% if user.is_anonymous%}
              <li><a href="{% url 'login' %}">Login</a></li>
              {% endif %}
            </ul>
        </nav>
    </header>
        {% block content %}
        {% endblock content %}
</body>
</html>

receipts/templates/accounts/create_account.html
{% extends "base.html" %}

{% block content %}

<main>
  <div>
    <h1>Create Account</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p}}
      <button type="submit">Create</button>
    </form>
  </div>
</main>

{% endblock content %}

receipts/templates/accounts/list_accounts.html
{% extends "base.html" %}

{% block content %}
<h1>My Accounts</h1>
<main>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Number</th>
        <th>Number of receipts</th>
      </tr>
    </thead>
    <tbody>
      {% for account in account_list %}
      <tr>
        <td>{{ account.name}}</td>
        <td>{{ account.number}}</td>
        <td>{{account.receipts.all|length}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>
{% endblock content %}

receipts/templates/categories/list_categories.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'create_category' %}">Create</a>

<main>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Number of receipts</th>
      </tr>
    </thead>
    <tbody>
      {% for expense in expensecategory_list %}
      <tr>
        <td>{{ expense.name }}</td>
        <td>{{ expense.receipts.all|length }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>

{% endblock content %}

receipts/templates/receipts/create_category.html
{% extends "base.html" %}

{% block content %}

<main>
  <div>
    <h1>Create Category</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p}}
      <button type="submit">Create</button>
    </form>
  </div>
</main>

{% endblock content %}

receipts/templates/receipts/create_receipt.html
{% extends "base.html" %}

{% block content %}

<main>
  <div>
    <h1>Create Receipt</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p}}
      <button type="submit">Create</button>
    </form>
  </div>
</main>

{% endblock content %}

receipts/templates/receipts/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <header>
        <nav>
        </nav>
    </header>
    <main>
       <h1>My Receipts</h1>
            <table>
                <thead>
                    <tr>
                        <th>Vendor</th>
                        <th>Total</th>
                        <th>Tax</th>
                        <th>Date</th>
                        <th>Category</th>
                        <th>Account</th>
                    </tr>
                </thead>
                <tbody>
                    {% for receipt in receipt_list %}
                        <tr>
                            <td>{{receipt.vendor}}</td>
                            <td>{{receipt.total}}</td>
                            <td>{{receipt.tax}}</td>
                            <td>{{receipt.date|date:"m/d/y"}}</td>
                            <td>{{receipt.category}}</td>
                            <td>{{receipt.account}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
    </main>
</body>
</html>